### ISSUE TITLE
implement functions in CMatrix class that support some mathematical expressions  and some matrices declarations (task1)

### ISSUE THREAD

**Issue by ahmedibrahim6** [ahmedibrahim6/AsuMathLabG03#4]
expressions :     (./)   ,    (.*)   ,    (.+)  ,    (.-)  ,   (.^)

declarations : rand() , eye() , zeroes(), ones ()

task1 :  support mathematical expressions above by implementing functions in CMatrix class

**Comment by MohamedRaheem** [comment]
[CMatrix.txt](https://github.com/ahmedibrahim6/AsuMathLabG03/files/1504250/CMatrix.txt)

This file has the following mathematical expressions (.+  ./  .*  .-  .^)

[example.txt](https://github.com/ahmedibrahim6/AsuMathLabG03/files/1504254/example.txt)

This file has the test cases for the mathematical expressions in the above file

[output.txt](https://github.com/ahmedibrahim6/AsuMathLabG03/files/1504255/output.txt)

This file has the output of the above test cases
